# Generated by Django 3.1.7 on 2021-02-24 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_code', models.JSONField(default=users.models.Profile.get_activation_code, null=True)),
                ('is_public', models.BooleanField(default=False, help_text='If this setting is active, users can look up this profile based on your username and view all your public stores.', verbose_name='Make this profile public')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
