# Generated by Django 3.1.7 on 2021-02-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wants_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
