# Generated by Django 3.1.7 on 2021-03-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If this setting is active, users can look up this profile based on your username and view all your public JSON stores.', verbose_name='Make this profile public'),
        ),
    ]
