# Generated by Django 3.1.7 on 2021-02-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_wants_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jsonstore_count_max',
            field=models.IntegerField(default=25),
        ),
    ]
