# Generated by Django 3.1.7 on 2021-02-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210225_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='jsonstore_count_max',
        ),
        migrations.AddField(
            model_name='profile',
            name='max_store_data_size',
            field=models.IntegerField(default=5242880),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_user_all_stores_size',
            field=models.IntegerField(default=5242880),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_user_store_count',
            field=models.IntegerField(default=25),
        ),
    ]
