# Generated by Django 3.1.7 on 2021-02-25 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210225_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='max_user_all_stores_size',
            new_name='max_user_all_stores_data_size',
        ),
    ]
