# Generated by Django 3.1.7 on 2021-02-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210225_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='max_store_data_size',
        ),
        migrations.AddField(
            model_name='profile',
            name='max_user_store_data_size',
            field=models.IntegerField(default=2097152),
        ),
    ]
