# Generated by Django 3.1.7 on 2021-02-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210225_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_tier',
            field=models.CharField(default='free', max_length=128),
        ),
    ]
