# Generated by Django 3.1.7 on 2021-02-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_account_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='max_user_all_stores_data_size',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='max_user_store_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='max_user_store_data_size',
        ),
        migrations.AddField(
            model_name='profile',
            name='max_all_stores_data_size',
            field=models.IntegerField(default=1024),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_store_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_store_data_size',
            field=models.IntegerField(default=1024),
        ),
    ]
