# Generated by Django 3.1.7 on 2021-02-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210225_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='max_all_stores_data_size',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='max_store_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='max_store_data_size',
        ),
    ]
