# Generated by Django 3.1.7 on 2021-02-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210226_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activation_code',
        ),
    ]
