# Generated by Django 3.1.7 on 2021-02-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_profile_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_code',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
