# Generated by Django 3.1.7 on 2021-02-26 09:08

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activation_code',
            field=models.CharField(default=users.models.Profile.get_activation_code, max_length=128),
        ),
    ]
