# Generated by Django 3.1.7 on 2021-02-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonsaver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonstore',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Allow this store to be publicly accessible by name.'),
        ),
        migrations.AlterField(
            model_name='jsonstore',
            name='name',
            field=models.CharField(blank=True, help_text='Name will be lowercased and hyphenated for use in URLs.', max_length=128, null=True),
        ),
    ]
