# Generated by Django 3.1.7 on 2021-02-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonsaver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonstore',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
