# Generated by Django 3.1.6 on 2021-02-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonsaver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonitem',
            name='message',
            field=models.JSONField(),
        ),
    ]
