# Generated by Django 3.1.7 on 2021-02-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonsaver', '0002_jsonstore_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonstore',
            name='ref',
        ),
        migrations.AddField(
            model_name='jsonstore',
            name='name',
            field=models.CharField(blank=True, help_text='Note: Name will be converted to lowercase and hyphenated', max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonstore',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Make this store publicly accessible using the name as a lookup value'),
        ),
    ]
