# Generated by Django 3.1.7 on 2021-02-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonsaver', '0003_auto_20210220_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonstore',
            name='name',
            field=models.CharField(help_text='Note: Name will be converted to lowercase and hyphenated', max_length=128),
        ),
    ]
