from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import UserPasswordResetForm

app_name = 'users'

urlpatterns = [
    path('',
         views.users_root,
         name='users_root'),
    path('register/',
         views.UserRegisterView.as_view(),
         name='register'),
    path('activate/',
         views.users_root,
         name='users_activate_root'),
    path('activate/resend/',
         views.UserActivationEmailResend.as_view(),
         name='user_activation_email_resend'),
    path('activate/<str:activation_code>/',
         views.user_activate,
         name="user_activate"),
    path('login/',
         views.UserLoginView.as_view(),
         name='login'),
    path('login/recover-username/',
         views.UserUsernameRecoverView.as_view(),
         name='user_username_recover'),
    path('me/',
         views.UserDetailMeView.as_view(),
         name='user_detail_me'),
    path('me/update/upgrade-account/',
         views.UserUpdateAccountTierView.as_view(),
         name='user_update_account_tier'),
    path('me/update/email/',
         views.UserUpdateEmailView.as_view(),
         name='user_update_email'),
    path('me/update/email/<str:activation_code>/',
         views.user_update_email_confirm,
         name="user_update_email_confirm"),
    path('me/update/password/',
         auth_views.PasswordChangeView.as_view(
             template_name='users/password_change_form.html'),
         name='password_change'),
    path('forgot-password/',
         auth_views.PasswordResetView.as_view(
             form_class=UserPasswordResetForm,
             template_name='users/password_reset_form.html'),
         name='password_reset'),
    path('me/update/settings/',
         views.UserUpdateView.as_view(),
         name='user_update'),
    path('me/update/settings/profile-visibility/',
         views.UserUpdateIsPublicView.as_view(),
         name='user_update_is_public'),
    path('me/renew-api-key/',
         views.UserUpdateApiKeyView.as_view(),
         name='user_update_api_key'),
    path('me/delete-account/',
         views.UserDeleteView.as_view(),
         name='user_delete'),
    path('logout/',
         views.UserLogoutView.as_view(),
         name='logout'),
    path('public/<str:username>/',
         views.UserDetailPublicView.as_view(),
         name='user_detail_public'),
]
