from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('',
         views.users_root,
         name='users_root'),
    path('register/',
         views.UserRegisterView.as_view(),
         name='register'),
    path('activate/',
         views.users_root,
         name='users_activate_root'),
    path('activate/resend/',
         views.UserActivationEmailResend.as_view(),
         name='user_activation_email_resend'),
    path('activate/<str:activation_code>/',
         views.user_activate,
         name="user_activate"),
    path('login/',
         views.UserLoginView.as_view(),
         name='login'),
    path('me/',
         views.UserDetailView.as_view(),
         name='user_detail_me'),
    # path('me/update/',
    #      views.UserUpdateView.as_view(),
    #      name='user_update'),
    path('me/update/email/',
         views.UserUpdateEmailView.as_view(),
         name='user_update_email'),
    path('me/update/email/<str:activation_code>/',
         views.user_update_email_confirm,
         name="user_update_email_confirm"),
    path('me/update/settings/',
         views.UserUpdateProfileView.as_view(),
         name='user_update_profile'),
    path('me/update/api-key-reset/',
         views.UserUpdateApiKeyView.as_view(),
         name='user_update_api_key'),
    path('me/delete-account/',
         views.UserDeleteView.as_view(),
         name='user_delete'),
    path('logout/',
         views.UserLogoutView.as_view(),
         name='logout'),
    path('public/<str:username>/',
         views.UserDetailPublicView.as_view(),
         name='user_detail_public'),
]
